### ISSUE TITLE
Copy-paste typo?

### ISSUE THREAD

**Issue by adavidzh** [CMS-HGCAL/rpi-daq#7]
Is [this](https://github.com/CMS-HGCAL/rpi-daq/blob/python/src/gpiohb.c#L93) a (copy-paste) typo? Because the exact same action was taken [just above](https://github.com/CMS-HGCAL/rpi-daq/blob/python/src/gpiohb.c#L71); unclear what its function is.

**Comment by artlbv** [comment]
In the original file there is just a return for the high level:
https://github.com/CMS-HGCAL/rpi-daq/blob/master/gpiolib.c

**Comment by adavidzh** [comment]
Indeed, it looks like it creeped in in this [commit](https://github.com/CMS-HGCAL/rpi-daq/commit/c80fcb9a9ea39cb41c3b70548f425df8c8b0a143#diff-8fc134697bb6d6ba90cf899681e69c98R93).

**Comment by adavidzh** [comment]
Addressed as part of #8.
